on: workflow_dispatch
name: 🚀 Deploy website on api event
jobs:
    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2

            - name: Use Node.js 14
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: 🔨 Build Project
              run: |
                  yarn
                  yarn do:export:deploy

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.1.0
              with:
                  server: 'home.mnet-online.de'
                  username: 'simon'
                  password: 'k4!Q8+Gd'
                  local-dir: ./__sapper__/export/
                  server-dir: 'lsgWebsite/'
